dist: xenial
language: node_js
matrix:
  include:
    - node_js: 10
      env: COLLECT_COVERAGE=true
after_success:
  - if [[ "$COLLECT_COVERAGE" = "true" ]]; then bash <(curl -s https://codecov.io/bash123); fi
cache: npm
notifications:
  email:
    on_success: never
    on_failure: always
